{
'app.name':'汉智大数据',
'app.name.subtitle':'汉智大数据-{0}',
'app.name.subtitle.experimental':'汉智大数据体验',
'app.reloadPopup.link': '重新加载页面',
'app.reloadPopup.text': '正在尝试连接服务端...',
'app.reloadPopup.noClusterName.text': '获取集群名称失败，正在重新加载...',
'app.reloadPopup.header': '重新加载页面',
'app.redirectIssuePopup.header': '登录重定向问题',
'app.redirectIssuePopup.body': '若要单点登录，请确保Knox入口和汉智大数据服务启动于同一主机（host）或子域（subdomain）上。' +
  '<br/>或者使用本地登录页面的汉智大数据本地用户进行登录。<br/>' +
  '<a href="{0}" target="_blank">{0}</a>',

'app.loadingPlaceholder': '加载中...',
'app.versionMismatchAlert.title': '汉智大数据的服务端/Web客户端版本不匹配',
'app.versionMismatchAlert.body': '汉智大数据服务端和Web客户端版本不匹配：<br> ' +
  '<br>汉智大数据服务端: <strong>{0}</strong>' +
  '<br>汉智大数据Web客户端: <strong>{1}</strong><br>' +
  '<br>这类问题通常发生在升级汉智大数据平台后和浏览器缓存的Web客户端代码而产生冲突。' +
  '<br>执行不使用浏览器缓存的刷新（通常通过\'Ctrl+Shift+R\' （\'Cmd+Shift+R\' on OS X））来查看这个问题是否被解决。' +
  '<br>如果该问题仍然存在，请彻底清除浏览器缓存后再次点击该URL。' +
  '<br>请注意，您必须解决这个问题才能继续。',
'app.signout':'注销',
'app.settings':'设置',
'app.manageAmbari': '管理汉智大数据平台',
'app.aboutAmbari':'关于我们',
'app.settings.selectTimezone': '时区',
'app.settings.notshowBgOperationsPopup': '当启动操作时不显示该后台操作对话框',
'app.settings.notShowBgOperations': '当启动后台操作时，不再显示该对话框',
'app.settings.categories.general': '通用',
'app.settings.categories.locale': '语言环境',
'app.settings.noData': '无法获取设置内容',
'app.settings.no.view.privileges': '没有查看权限',
'app.settings.no.cluster.privileges': '没有集群权限',
'app.settings.admin.all.privileges': '该用户是汉智大数据平台的管理员账户，拥有全部权限。',
'app.settings.no.privileges': '该用户不具备任何权限。',
'app.settings.clusterRole': '集群角色',
'app.settings.viewPermissions': '查看权限',
'app.goToView': '前往查看',
'app.debugHiveQuery': '调试Hive查询',

'app.aboutAmbari.getInvolved': '加入我们!',
'app.aboutAmbari.version': '版本号',
'app.aboutAmbari.licensed': 'Licensed under the Apache License，Version 2.0',

'apply':'apply',
'and':'and',
'none':'none',
'all':'all',
'minimum':'minimum',
'from':'From',
'to':'To',
'ok':'OK',
'as':'as',
'on':'on',
'in':'in',
'any': 'Any',
'more':'more',
'yes':'Yes',
'no':'No',
'add': 'Add',
'op': 'op',
'ops': 'ops',
'or': 'or',
'then': 'then',
'it': 'it',


'common.access':'访问',
'common.learnMore':'了解更多',
'common.showDetails':'查看详情',
'common.back':'返回',
'common.prev':'上一页',
'common.next':'下一页',
'common.host':'主机',
'common.hosts':'主机',
'common.services':'服务',
'common.group':'用户组',
'common.groups':'用户组',
'common.progress':'进度',
'common.status':'状态',
'common.action':'启用',
'common.refresh':'刷新',
'common.remove':'移除',
'common.retry':'重试',
'common.skip':'跳过',
'common.filter': '过滤器',
'common.rollBack':'回滚',
'common.show':'显示',
'common.hide':'隐藏',
'common.cancel':'取消',
'common.apply':'应用',
'common.done':'完成',
'common.failed':'失败',
'common.service': '服务',
'common.version':'版本',
'common.downgrade':'降级',
'common.description':'描述',
'common.default':'默认',
'common.client':'客户端',
'common.zookeeper':'ZooKeeper',
'common.hbase':'HBase',
'common.regionServer':'RegionServer',
'common.taskTracker':'TaskTracker',
'common.dataNode':'DataNode',
'common.more': '更多...',
'common.print':'打印',
'common.deploy':'部署',
'common.generate.blueprint':'生成蓝图',
'common.message':'消息',
'common.tasks':'任务',
'common.open':'打开',
'common.copy':'复制',
'common.complete':'完成',
'common.completed':'已完成',
'common.metrics':'性能指标',
'common.timeRange':'时间范围',
'common.name':'名称',
'common.key':'Key',
'common.value':'Value',
'common.ipAddress':'IP地址',
'common.rack':'机架',
'common.cpu':'CPU',
'common.cores': '核数',
'common.cores.cpu': '核数（CPU）',
'common.ram':'内存',
'common.disabled':'禁用',
'common.enabled':'启用',
'common.enableAll':'全部启用',
'common.disableAll':'全部禁用',
'common.disk':'硬盘',
'common.diskUsage':'硬盘使用情况',
'common.last':'最近',
'common.loadAvg':'平均负载',
'common.components':'组件',
'common.component':'组件',
'common.quickLinks':'快速链接',
'common.save':'保存',
'common.saveAnyway':'强制保存',
'common.servers':'服务器',
'common.clients':'客户端',
'common.all.clients':'全部客户端',
'common.user': '用户',
'common.users': '用户',
'common.issues': '问题',
'common.os':'操作系统',
'common.oss':'操作系统',
'common.memory':'内存',
'common.maximum':'最大值',
'common.started':'已开始',
'common.start':'启动',
'common.stop':'停止',
'common.pause':'暂停',
'common.end':'结束',
'common.decommission':'停用',
'common.recommission':'重新启用',
'common.failure': '失败',
'common.type': '类型',
'common.direction': 'Direction',
'common.close': '关闭',
'common.warning': '警告',
'common.critical': '严重',
'common.information': '信息',
'common.all':'全部',
'common.success': '成功',
'common.fail':'失败',
'common.error': '错误',
'common.loading': '加载',
'common.search': '搜索',
'common.confirm': '确认',
'common.upgrade': '升级',
'common.reUpgrade': '升级重试',
'common.reDowngrade': '降级重试',
'common.security':'安全',
'common.kerberos':'Kerberos',
'common.cluster':'集群',
'common.repositories':'仓库',
'common.stack.versions':'组件版本',
'common.versions':'版本列表',
'common.upgrade.history':'升级历史记录',
'common.serviceAccounts': '服务账户列表',
'common.add': '添加',
'common.edit': '编辑',
'common.delete': '删除',
'common.duplicate': '副本',
'common.disable': '禁用',
'common.enable': '启用',
'common.empty': '清空',
'common.override':'覆盖',
'common.undo':'撤销',
'common.details':'详情',
'common.stats':'统计',
'common.abort': '终止',
'common.aborted': '已终止',
'common.misc': '其它选项',
'common.userSettings': '用户设置',
'common.aboutAmbari': '关于汉智大数据平台',
'common.notAvailable': '不可用',
'common.na': 'n/a',
'common.operations': '操作',
'common.startTime': '开始时间',
'common.duration': '持续时间',
'common.reinstall': '重装',
'common.revert': '重置',
'common.errorPopup.header': '发生一个错误',
'common.use': '使用',
'common.stacks': '技术栈',
'common.stack': '技术栈',
'common.reset': '复位',
'common.reset.default': '重置为默认',
'common.resume': '简介',
'common.path': '路径',
'common.patch': '补丁',
'common.package': '包',
'common.proceed': '继续',
'common.proceedAnyway': '无论如何继续',
'common.exitAnyway': '强制结束',
'common.process': '过程',
'common.property': '属性',
'common.installed': '安装',
'common.persist.error' : '在汉智大数据服务端保存web客户端状态时出错，服务端返回以下错误信息：',
'common.update.error' : '从汉智大数据服务端获取web客户端状态时出错',
'common.tags': '标签',
'common.important': '重要',
'common.important.strong': '<strong>重点：</strong>',
'common.allServices':'所有服务',
'common.move':'移动',
'common.change': '修改',
'common.overrides': '覆盖',
'common.properties': '属性',
'common.conf.group': '配置分组',
'common.ignore': '忽略',
'common.restart': '重启',
'common.discard': '丢弃',
'common.actions': '操作',
'common.maintenance': '维护',
'common.passive_state': '维护模式',
'common.select': '选择',
'common.selected': '选择',
'common.password': '密码',
'common.url': 'URL',
'common.advanced': '高级',
'common.download': '下载',
'common.current': '当前',
'common.additional': '补充',
'common.time.start': '开始时间',
'common.time.end': '结束时间',
'common.hostLog.popup.logDir.path':'日志路径',   // TODO, this hardcoded path needs to be removed.
'common.hostLog.popup.outputLog.value': 'output-{0}.txt',
'common.hostLog.popup.errorLog.value': 'errors-{0}.txt',
'common.maintenance.task': '切换维护模式',
'common.installRepo.task': '下载程序包',
'common.used': '使用',
'common.free': '空闲',
'common.type.string': '字符串',
'common.type.number': '数字',
'common.author': '创建者',
'common.notes': '备注',
'common.view': '查看',
'common.compare': '比较',
'common.latest': '最新',
'common.custom': '自定义',
'common.continueAnyway': '强制继续',
'common.property.undefined': '未定义',
'common.summary': '总览',
'common.configs': '配置',
'common.configuration': '配置',
'common.unknown': '未知',
'common.install': '安装',
'common.alertDefinition': '警报',
'common.prerequisites': '前提',
'common.finalize': '完成',
'common.severity': '严重',
'common.dismiss': '返回',
'common.stdout': '标准输出',
'common.stderr': '标准错误',
'common.structuredOut': 'structured_out',
'common.fileName': '文件名',
'common.file': '文件夹',
'common.days': '天',
'common.hours': '小时',
'common.minutes': '分钟',
'common.seconds': '秒',
'common.milliseconds': '毫秒',
'common.configGroup': '配置组',
'common.expression': '表达式',
'common.dataSet': '设置时间',
'common.label': '标签',
'common.preview': '预览',
'common.options': '选项',
'common.scope': '范围',
'common.clone': '克隆',
'common.removed': '移除',
'common.testing': '测试',
'common.noData': '无数据',
'common.export': '导出',
'common.csv': 'CSV',
'common.json': 'JSON',
'common.timestamp': '时间戳',
'common.timezone': '时区',
'common.loading.eclipses': '加载中...',
'common.optional': '可选项',
'common.propertyType': '属性类型',
'common.running': '运行',
'common.stopped': '停止',
'common.enter': '进入',
'common.timeout.warning.popup.header': '自动注销',
'common.timeout.warning.popup.body.before': '您将自动注销',
'common.timeout.warning.popup.body.after': '秒内不活动',
'common.timeout.warning.popup.primary': '保持登录',
'common.timeout.warning.popup.secondary': '立即注销',
'common.openNewWindow': '打开新窗口',
'common.fullLogPopup.clickToCopy': '复制',
'common.nothingToDelete': '无可用删除',
'common.exclude': '排除',
'common.include': '包含',
'common.exclude.short': '排除',
'common.include.short': '包含',
'common.filters': '过滤',
'common.keywords': '关键字',
'common.levels': '水平',
'common.extension': '扩展',
'common.logs': '日志',
'common.warn.message': '<div class="alert alert-warning">{0}</div>',
'common.link': '链接',
'common.from.version': '版本',
'common.to.version': '版本',
'common.start.time': '开始时间',
'common.end.time': '结束时间',
'common.rolling': '滚动',
'common.express': '表达式',
'common.hostOrdered': '主机命令',
'common.rolling.downgrade': '滚动升级',
'common.express.downgrade': '快速降级',

'models.alert_instance.tiggered.verbose': "{0}<br>检查{1}",
'models.alert_definition.triggered.verbose': "{0}",
'models.alert_definition.triggered.checked': "状态已改变：{0}\n最近检查：{1}",
'models.alert_definition.check.retry': "Alert Check {0} out of {1}",

'passiveState.turnOn':'开启维护模式',
'passiveState.turnOff':'关闭维护模式',
'passiveState.turnOnFor':'开启{0}维护模式',
'passiveState.turnOffFor':'关闭{0}维护模式',
'passiveState.disabled.impliedFromHighLevel':'{0}已处于维护模式，因为{1}处于维护模式。',
'passiveState.disabled.impliedFromServiceAndHost':'{0}已处于维护模式，因为{1}和{2}处于维护模式。',

'requestInfo.installComponents':'安装组件',
'requestInfo.installKerbeorosComponents':'kerberos组件安装',
'requestInfo.installServices':'安装服务',
'requestInfo.kerberosService': 'Kerberos服务安装',
'requestInfo.startServices':'开启服务',
'requestInfo.startAddedServices':'启动添加服务',
'requestInfo.stopAllServices':'停止所有服务',
'requestInfo.startAllServices':'开启所有服务',
'requestInfo.startHostComponent':'开始',
'requestInfo.startHostComponent.datanode':'启动DataNode',
'requestInfo.startHostComponent.nodemanager':'启动NodeManager',
'requestInfo.startHostComponent.hbase_regionserver':'启动RegionServer',
'requestInfo.startHostComponents':'启动组件',
'requestInfo.upgradeHostComponent':'升级',
'requestInfo.stopHostComponent':'停止',
'requestInfo.installHostComponent':'安装',
'requestInfo.installNewHostComponent':'安装',
'requestInfo.refreshComponentConfigs':'刷新{0}配置',
'requestInfo.stop':'停止{0}',
'requestInfo.start':'开启{0}',
'requestInfo.unspecified':'未指定请求名称',
'requestInfo.kerberizeCluster': 'Kerberize集群',

'hostPopup.noServicesToShow':'无服务可显示',
'hostPopup.noHostsToShow':'无主机可显示',
'hostPopup.noTasksToShow':'无任务可显示',
'hostPopup.status.category.all':'全部（{0}）',
'hostPopup.status.category.pending':'挂起（{0}）',
'hostPopup.status.category.inProgress':'执行中（{0}）',
'hostPopup.status.category.failed':'失败（{0}）',
'hostPopup.status.category.success':'成功（{0}）',
'hostPopup.status.category.aborted':'中止（{0}）',
'hostPopup.status.category.timedout':'连接超时（{0}）',
'hostPopup.header.postFix':' 后台运行（{0}）操作',
'hostPopup.serviceInfo.showMore':'显示更多...',
'hostPopup.bgop.abortRequest.title': '中止操作',
'hostPopup.bgop.abortRequest.confirmation.body': '确定要中止\'{0}\'操作',
'hostPopup.bgop.abortRequest.reason': '被用户中止',
'hostPopup.bgop.abortRequest.modal.header': '中止发送请求',
'hostPopup.bgop.abortRequest.modal.body': '中止请求<strong>{0}</strong>已发送到服务器。注意：中止请求生效之前，已经运行任务的完成或失败需要一些时间。',
'hostPopup.bgop.sourceRequestSchedule.running': '可以中止后续的批处理请求',
'hostPopup.bgop.sourceRequestSchedule.aborted': '已经中止后续的批处理请求',
'hostPopup.bgop.abort.rollingRestart': '中止滚动重启',
'hostPopup.warning.alertsTimeOut': '{0}维护模式已开启，这将花费几分钟修改到{1}',
'hostPopup.reccomendation.beforeDecommission': '{0}维护模式需先将其停用',
'hostPopup.setRackId.success': '更新机架Id到\"{0}\"，这将花费几分钟等待其刷新。',
'hostPopup.setRackId.error': '更新机架ID失败',
'hostPopup.setRackId.invalid': '应以斜杠开始它可以包含字母、数字、点号、破折号和斜杠。应该少于255个符号。',
'hostPopup.RackId': '机架',
'hostPopup.recommendation.beforeDecommission': '{0}维护模式先将其停用',

'question.sure':'您确定吗？',
'question.sure.restart':'您确定要重启{0}吗？',
'question.sure.start':'您确定启动{0}吗',
  'question.sure.stop':'您确定要停止{0}吗？',
'question.sure.move':'您确定要移动{0}吗？',
'question.sure.refresh':'您确定要在{0}上重启所有客户端吗？',
'question.sure.maintenance':'您确定要启用{0}的维护模式吗？',
'question.sure.upgrade':'您确定要升级{0}吗？',
'question.sure.decommission':'您确定要停用{0}吗？',
'question.sure.recommission':'您确定要重用{0}吗？',
'question.sure.startAll':'您确定要开启所有的组件吗？',
'question.sure.stopAll':'您确定要停止所有的组件吗？',
'question.sure.restartAll':'您确定要重新启动所有组件吗？',

'popup.highlight':'点击高亮显示',
'popup.confirmation.commonHeader':'确认',
'popup.confirmation.refreshYarnQueues.body':'在更改容量调度配置后，强烈建议<strong>刷新YARN队列</strong>。您想继续吗？',
'popup.warning.refreshYarnQueues.body': '<div class =“alert alert-warning”> <strong>警告：</strong>队列配置更改可能会影响Hive LLAP使用的队列。可能需要重新配置或重新启动Hive LLAP。</div>',
'popup.confirmation.refreshYarnQueues.buttonText':'刷新Yarn队列',
'popup.confirmation.hsiRestart.body':'在更改Hive LLAP大小配置后，强烈建议<strong>重新启动HiveServer2 Interactive </strong>。您想继续吗？',
'popup.confirmation.hsiRestart.buttonText':'重新启动HiveServer2 Interactive',
'popup.prompt.commonHeader':'提示',
'popup.confirmationFeedBack.sending':'发送中...',
'popup.confirmationFeedBack.query.fail':'请求失败',

'popup.clusterCheck.failedOn':'失败于：',
'popup.clusterCheck.reason':'原因：',
'popup.clusterCheck.Upgrade.header':'升级到{0}',
'popup.clusterCheck.Upgrade.fail.title':'要求',
'popup.clusterCheck.Upgrade.fail.alert':'您<strong>必须</strong>满足这些要求，然后才能继续。',
'popup.clusterCheck.Upgrade.bypassed-failures.title': '可绕过的错误',
'popup.clusterCheck.Upgrade.bypassed-failures.alert': '错误允许被绕过，因为stack.upgrade.bypass.prechecks设置为true。强烈建议您研究下这些错误。',
'popup.clusterCheck.Upgrade.warning.title': '警告',
'popup.clusterCheck.Upgrade.warning.alert': '<strong>建议</strong>您更正警告，但这不是必需的',
'popup.clusterCheck.Upgrade.configsMerge.title': '配置更改',
'popup.clusterCheck.Upgrade.configsMerge.alert': '在升级期间，以下配置更改将被应用',
'popup.clusterCheck.Upgrade.configsMerge.configType': '配置类型',
'popup.clusterCheck.Upgrade.configsMerge.propertyName': '属性名称',
'popup.clusterCheck.Upgrade.configsMerge.currentValue': '当前值',
'popup.clusterCheck.Upgrade.configsMerge.recommendedValue': '推荐值',
'popup.clusterCheck.Upgrade.configsMerge.resultingValue': '结果值',
'popup.clusterCheck.Upgrade.configsMerge.deprecated': '属性已被弃用',
'popup.clusterCheck.Upgrade.configsMerge.willBeRemoved': '将被删除',
'popup.clusterCheck.Upgrade.configsRecommend.alert': '我们检测到需要更新以下属性，但是由于它们已被定义，所以不能自动执行。请手动查看这些属性，并在必要时手动更新它们。',
'popup.clusterCheck.Upgrade.configsRecommend.title': '推荐的配置更改：手动审核',
'popup.clusterCheck.Security.header': '启用安全模式',
'popup.clusterCheck.Security.title': '不满足安全模式要求',
'popup.clusterCheck.Security.alert': '您必须满足以下要求才能启用安全模式。',

'popup.invalid.KDC.header': '管理员会话过期错误',
'popup.invalid.KDC.msg': '请输入管理员用户名和密码',
'popup.invalid.KDC.admin.principal': '管理员用户名',
'popup.invalid.KDC.admin.password': '管理员密码',

'popup.dependent.configs.header': '依赖配置',
'popup.dependent.configs.title.recommendation': '根据您的配置更改，汉智大数据推荐更改以下从属配置。',
'popup.dependent.configs.title.values': '汉智大数据将更新所有检查的配置并更改为<b>推荐值</b>。取消选中的任何配置以保留<b>当前值</b>。',
'popup.dependent.configs.title.required': '需要更改以下配置并自动应用。',
'popup.dependent.configs.table.recommended': '推荐更改',

'popup.dependent.configs.table.required': '需要更改',
'popup.dependent.configs.table.saveProperty': '保存属性',
'popup.dependent.configs.table.initValue': '初始值',
'popup.dependent.configs.table.currentValue': '当前值',
'popup.dependent.configs.table.recommendedValue': '推荐值',
'popup.dependent.configs.table.newValue': '新值',
'popup.dependent.configs.table.undefined': '未定义的属性',
'popup.dependent.configs.table.removed': '已移除的属性',


'popup.dependent.configs.select.config.group.header': '选择配置组',
'popup.dependent.configs.select.config.group.no.groups': '当前服务没有配置组',
'popup.dependent.configs.select.config.group': '请选择您要保存依赖属性的配置组',

'popup.dependent.configs.dependencies.config.singular': '{0}配置更改',
'popup.dependent.configs.dependencies.config.plural': '{0}多个配置更改',
'popup.dependent.configs.dependencies.service.singular': '在{0}服务里',
'popup.dependent.configs.dependencies.service.plural': '在{0}的多个服务里',

'popup.dependent.configs.dependencies.for.groups': '您正在更改非默认组，请选择您想要从其他服务保存相关配置的配置组',

'popup.jdkValidation.header': '不支持的JDK',
'popup.jdkValidation.body': '{0}技术栈需要JDK{1}，但是汉智大数据平台配置的JDK{2}。这可能会导致运行集群的时出现错误或问题。',
'popup.logTail.header': '文件名',
'popup.logTail.openInLogSearch': '打开日志搜索',

'login.header':'登录',
'login.message.title':'登录信息',
'login.username':'用户名',
'login.loginButton':'登录',
'login.error.bad.credentials':'无法登录，无效的用户名/密码组合',
'login.error.disabled':'无法登录，无效的用户名/密码组合',
'login.error.bad.connection':'无法连接到汉智大数据服务器。请确认汉智大数据服务正在运行，您可以从本机访问汉智大数据服务。',

'titlebar.alerts.noAlerts': '没有警报',

'graphs.noData.title': '无数据',
'graphs.noData.message': '无可用数据',
'graphs.noData.tooltip.title': '无可用数据。汉智大数据平台的Metrics服务可能未安装或无法访问',
'graphs.noDataAtTime.message': '该时间段内没有可用的数据',
'graphs.error.title': '错误',
'graphs.error.message': '获取图表（{0}：{1}）的数据时出现问题',
'graphs.timeRange.hour': '最近1小时',
'graphs.timeRange.twoHours': '最近2小时',
'graphs.timeRange.fourHours': '最近4小时',
'graphs.timeRange.twelveHours': '最近12小时',
'graphs.timeRange.day': '最近24小时',
'graphs.timeRange.week': '最近1星期',
'graphs.timeRange.month': '最近1个月',
'graphs.timeRange.year': '最近1年',
'graphs.tooltip.title': '点击放大',

'users.userName.validationFail': '仅推荐小写字母和数字；必须以字母开头',
'host.spacesValidation': '不能包含空格',

'services.hdfs.rebalance.title' : 'HDFS重新平衡',
'services.ganglia.description':'Ganglia Metrics Collection系统',
'services.hdfs.description':'Apache Hadoop分布式文件系统',
'services.glusterfs.description':'Apache Hadoop兼容文件系统（必须手动安装）',
'services.sqoop.description':'用于在Apache Hadoop和结构化数据存储（如关系数据库）之间传输批量数据的工具',
'services.pig.description':'用于分析大数据集的脚本平台',
'services.hive.description':'数据仓库系统用于特殊查询和分析大型数据集和表以及存储管理服务',
'services.oozie.description':'用于工作流协调和执行Apache Hadoop作业的系统',
'services.zookeeper.description':'提供高度可靠的分布式协调的集中式服务',
'services.hbase.description':'非关系性分布式数据库和集中式服务进行配置管理和同步',
'services.hive.databaseComponent':'数据库服务',
'services.mapreduce2.description':'Apache Hadoop NextGen MapReduce（client libraries）',
'services.yarn.description':'Apache Hadoop NextGen MapReduce（YARN）',
'services.tez.description':'Tez是YARN上面编写的下一代Hadoop查询处理框架',
'services.falcon.description': 'Falcon mirroring引擎',
'services.storm.description': 'Apache Hadoop Stream处理框架',
'services.storm.configs.range-plugin-enable.dialog.title': '启用STORM Ranger',
'services.storm.configs.range-plugin-enable.dialog.message': '启用STORM的Ranger插件仅在安全集群上有效',


'services.alerts.head':'您有{0}个严重的警报通知。',
'services.alerts.OK.timePrefixShort': '确定',
'services.alerts.WARN.timePrefixShort': '警告',
'services.alerts.CRIT.timePrefixShort': '严重',
'services.alerts.MAINT.timePrefixShort': '维护',
'services.alerts.UNKNOWN.timePrefixShort': '未知',
'services.alerts.OK.timePrefix': '{0}正常',
'services.alerts.WARN.timePrefix': '{0}警告',
'services.alerts.CRIT.timePrefix': '{0}严重',
'services.alerts.MAINT.timePrefix': '{0}维护',
'services.alerts.UNKNOWN.timePrefix': '{0}未知',
'services.alerts.lastCheck': '上次检查的{0}',
'services.alerts.brLastCheck': '<br>上次检查的{0}',
'services.alerts.occurredOn': '发生在{0}，{1}',
'services.alerts.goToService': '前往服务',
'services.alerts.goTo': '前往{0}',

'services.summary.selectHostForComponent': '选择要添加{0}组件的主机',
'services.summary.allHostsAlreadyRunComponent': '所有主机已运行{0}组件',

'topnav.logo.href':'/＃/main/dashboard',
'topnav.help.href':'https://cwiki.apache.org/confluence/display/AMBARI/Ambari',

'installer.header':'集群安装向导',
'installer.navigation.warning.header':'导航警告',

'installer.noHostsAssigned':'没有主机被分配',
'installer.slaveComponentHosts.selectHosts':'选择这个组的主机',
'installer.slaveComponentHostsPopup.header':'选择属于{0}组的主机',

'installer.controls.slaveComponentGroups':'组群',
'installer.controls.serviceConfigPopover.title':'{0}<br><small>{1}</small>',
'installer.controls.checkConnection.popover':'此操作将检查来自汉智大数据平台服务端主机的{0}主机和端口的可访问性',
'installer.controls.serviceConfigMultipleHosts.other':'其他',
'installer.controls.serviceConfigMultipleHosts.others':'其他的{0}',
'installer.controls.serviceConfigMasterHosts.header':'{0}主机',
'installer.controls.slaveComponentChangeGroupName.error':'此名称的组已存在',

'installer.step0.header':'开始',
'installer.step0.body.header':'开始',
'installer.step0.body':'该向导将引导您完成集群安装过程。首先，请命名您的新集群。',
'installer.step0.clusterName':'命名集群',
'installer.step0.clusterName.tooltip.title':'集群名称',
'installer.step0.clusterName.tooltip.content':'输入一个唯一的集群名称',
'installer.step0.clusterName.error.required':'集群名称是必填项',
'installer.step0.clusterName.error.tooLong':'集群名称太长',
'installer.step0.clusterName.error.whitespace':'集群名称不能包含空格',
'installer.step0.clusterName.error.specialChar':'集群名称不能包含特殊字符',

'installer.step1.header':'选择版本',
'installer.step1.body':'选择您的集群的软件版本和交付方式',
'installer.step1.repo.body':'使用公共仓库需要Internet连接。使用本地仓库需要您将软件配置在网络中可用的仓库中。',
'installer.step1.addVersion.title':'添加版本',
'installer.step1.changeVersion.defaultVersion':'定义默认版本',
'installer.step1.selectUseRepoOptions.public':'使用公共仓库',
'installer.step1.selectUseRepoOptions.public.networkLost.button':'不可用',
'installer.step1.selectUseRepoOptions.public.networkLost':'为什么没选该项？',
'installer.step1.selectUseRepoOptions.public.networkLost.popup.title': '未选择公共仓库选项',
'installer.step1.selectUseRepoOptions.public.networkLost.popup.msg': '汉智大数据平台无法确认对公共仓库的访问，这意味着您可能没有Internet访问，并且将无法使用“公共仓库”选项来安装软件。您的选择：',
'installer.step1.selectUseRepoOptions.public.networkLost.popup.msg1': '配置主机以访问网络。',
'installer.step1.selectUseRepoOptions.public.networkLost.popup.msg2': '如果您使用的是网络代理，请参考汉智大数据文档，了解如何配置汉智大数据使用网络代理。',
'installer.step1.selectUseRepoOptions.public.networkLost.popup.msg3': '使用本地仓库选项',
'installer.step1.selectUseRepoOptions.public.networkLost.popup.msg4': '如果您没有Internet访问并选择此选项，则将导致仓库基本URL验证失败。',
'installer.step1.selectUseRepoOptions.public.select':'选择版本',
'installer.step1.selectUseRepoOptions.local':'使用本地仓库',
'installer.step1.usePublicRepo.ReposList.empty':'没有其他版本',
'installer.step1.usePublicRepo.viewRepos':'查看仓库',
'installer.step1.useLocalRepo.uploadFile': '上传版本定义文件',
'installer.step1.useLocalRepo.uploadFile.error.title': '上传版本定义文件出错',
'installer.step1.useLocalRepo.getSurpottedOs.error.title': '无法获得支持的操作系统类型',
'installer.step1.useLocalRepo.addRepo.button': '添加仓库',
'installer.step1.addVersion': '添加版本',
'installer.step1.addVersion.stackChanged.popup.body': '技术栈从{0}更改为{1}。',
'installer.step1.useLocalRepo.enterUrl': '版本定义文件URL',
'installer.step1.useLocalRepo.enterUrl.placeholder': '输入版本定义文件的URL',
'installer.step1.useLocalRepo.readButton': '读取版本信息',
'installer.step1.useLocalRepo.infoForm.details.title': '详细信息',
'installer.step1.useLocalRepo.infoForm.details.stackName': '技术栈名称',
'installer.step1.useLocalRepo.infoForm.details.displayName': '显示名称',
'installer.step1.useLocalRepo.infoForm.details.version': '版本',
'installer.step1.useLocalRepo.infoForm.details.actualVersion': '实际版本',
'installer.step1.useLocalRepo.infoForm.content.title': '内容',
'installer.step1.useLocalRepo.infoForm.content.empty': '无内容可展示',
'installer.step1.useLocalRepo.infoForm.alert.baseUrl': '为您正在配置的操作系统提供基本URL。',
'installer.step1.useLocalRepo.infoForm.alert.warning': '一些仓库验证失败。如果您确定URL正确，请更改基本URL或跳过验证',
'installer.step1.advancedRepo.title':'高级仓库选项',
'installer.step1.advancedRepo.message':'自定义仓库用于下载技术栈软件包的基本URL。如果您的主机无法访问Internet，则必须创建一个可以由所有主机访问的技术栈仓库的本地镜像，并使用这些基本URL。',
'installer.step1.advancedRepo.importantMassage':'<b>重要:</b>当使用本地镜像仓库时，您只需要为操作系统提供正在安装的技术栈的基本URL，而不需选择所有其他仓库。',
'installer.step1.advancedRepo.localRepo.error.modifyUrl':'必须修改本地仓库URL',
'installer.step1.advancedRepo.localRepo.error.noUrl':'本地仓库需要基本URL',
'installer.step1.advancedRepo.localRepo.column.baseUrl':'基本URL',
'installer.step1.advancedRepo.localRepo.label.os':'操作系统',
'installer.step1.advancedRepo.localRepo.label.baseUrl':'仓库基本URL',
'installer.step1.advancedRepo.localRepo.label.stack':'技术栈',
'installer.step1.advancedRepo.localRepo.placeholder': '输入基本URL或者删除此操作系统',
'installer.step1.advancedRepo.skipValidation.tooltip':'警告：这仅适用于高级用户。如果要跳过仓库基本URLs的验证，请使用此选项。',
'installer.step1.advancedRepo.useRedhatSatellite.tooltip':'禁用分布式仓库，并改用RedHat Satellite / Spacewalk通道',
'installer.step1.advancedRepo.useRedhatSatellite.disabled.tooltip':'在使用公共仓库时不可使用RedHat Satellite / Spacewalk',
'installer.step1.advancedRepo.skipValidation.message':'跳过仓库基本URL验证（高级）',
'installer.step1.advancedRepo.useRedhatSatellite.message': '使用RedHat Satellite/Spacewalk',
'installer.step1.advancedRepo.useRedhatSatellite.warning': '通过选择<b>“使用RedHat Satellite/Spacewalk”</b>进行软件仓库,' +
  '您负责在Satellite/Spacewalk中配置仓库通道，并确认集群中主机上所选的<b>技术栈版本</b>的仓库是可用的。' +
  '更多相关信息，请参阅汉智大数据文档。',
'installer.step1.addOs.disabled.tooltip':'所有操作系统添加完毕',
'installer.step1.attentionNeeded':'<b>注意:</b>仓库至少需要一个操作系统的基本URL，然后才能继续，请确保它们的协议格式正确。',
'installer.step1.invalidURLAttention': '<b>注意：</b>在继续之前，请确保所有仓库URL都有效。',
'installer.step1.checkAtLeastOneAttention': '<b>注意：</b>请检查至少一个仓库。',
'installer.step1.retryRepoUrls': '点击<b>这里</b>重试。',

'installer.step2.header':'安装选项',
'installer.step2.body':'输入要包含在集群中的主机，并提供您的SSH密钥。',
'installer.step2.targetHosts':'目标主机',
'installer.step2.targetHosts.info':'使用完全限定域名（FQDN）输入主机，每行一个',
'installer.step2.hostPattern.tooltip.title':'模式表达式',
'installer.step2.hostPattern.tooltip.content':'您可以使用模式表达式来指定多个目标主机。例如，要通过host10.domain指定host01.domain，请在目标主机输入框中输入host[01-10].domain。',
'installer.step2.hostName.error.required':'您必须指定至少一个目标主机名称',
'installer.step2.hostName.error.already_installed':'这些主机都已经是集群的一部分',
'installer.step2.hostName.error.notRequired':'如果不使用SSH自动配置主机，主机名将被忽略',
'installer.step2.hostName.error.invalid':'无效主机名',
'installer.step2.hostName.pattern.header':'主机名模式表达式',
'installer.step2.sshKey':'主机注册信息',
'installer.step2.sshKey.error.required':'需要SSH私钥',
'installer.step2.passphrase.error.match':'密码不匹配',
'installer.step2.manualInstall.label':'不要使用SSH自动配置主机',
'installer.step2.manualInstall.info':'通过不使用SSH连接到目标主机，您必须手动安装和' +
  '启动每个主机上的汉智大数据代理，以使向导执行必要的配置和' +
  '软件安装。',
'installer.step2.advancedOption':'高级选项',
'installer.step2.repoConf':'软件仓库配置文件路径',
'installer.step2.advancedOptions.header':'高级选项',
'installer.step2.localRepo.label_use':'使用a',
'installer.step2.localRepo.label_instead':'取代从Internet下载软件包',
'installer.step2.localRepo.error.required':'需要本地仓库文件路径',
'installer.step2.localRepo.tooltip.title':'本地软件库',
'installer.step2.localRepo.tooltip.content': '集群安装需要访问Internet才能获取软件' +
  '从远程仓库。 在某些情况下，无法使用足够的带宽，并且您希望防止一遍又一遍的下载' +
  '来自远程仓库的软件包.其他时候，集群中的主机无法使用Internet访问' +
  '在这种情况下，您必须设置您的计算机可以在本地访问的仓库的版本，这称为<b>本地软件仓库</b>',
'installer.step2.javaHome.label' : ' 64-bit JDK路径',
'installer.step2.javaHome.tooltip.title' : 'JAVA_HOME',
'installer.step2.javaHome.tooltip.content' : ' 64-bit JAVA_HOME路径。汉智大数据默认使用/usr/jdk/jdk1.6.0_31，您可以指定一个包含JDK的路径来覆盖<br/>注意：此路径对集群的<b>所有</b>主机都有效。',
'installer.step2.javaHome.tooltip.placeholder' : '/usr/jdk/jdk1.6.0_31',
'installer.step2.automaticInstall.tooltip.title':'自动注册',
'installer.step2.automaticInstall.tooltip.content':'在安装集群之前，汉智大数据将在每个主机上自动安装和注册汉智大数据代理。'
}